config/routes.rb
Rails.application.routes.draw do

  get 'pages/landing'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :pokemons
  resources :poke_users

  root 'pages#landing'

  resources :users, only: [:index] do
    resources :poke_users, only: [:index] do
      member do
        get 'lvlup'
      end
    end
  end

end

app/models/poke_user.rb
class PokeUser < ActiveRecord::Base
  belongs_to :pokemon
  belongs_to :user

  before_save :set_default_lvl

  def set_default_lvl
    self.level = level || 5
  end


end

app/controllers/poke_users_controller.rb
class PokeUsersController < ApplicationController
  before_action :set_poke_user, only: [:show, :edit, :update, :destroy, :lvlup]
  before_action :authenticate_user!
  # GET /poke_users
  # GET /poke_users.json
  def index
    @user = User.find(params[:user_id])
    @poke_users = @user.poke_users
  end

  # GET /poke_users/1
  # GET /poke_users/1.json
  def show
  end

  # GET /poke_users/new
  def new
    @poke_user = PokeUser.new
  end

  # GET /poke_users/1/edit
  def edit
  end

  # POST /poke_users
  # POST /poke_users.json
  def create
    @poke_user = PokeUser.new(poke_user_params)
    @poke_user.user = current_user

    respond_to do |format|
      if @poke_user.save
        format.html { redirect_to user_poke_users_path(current_user), notice: 'Poke user was successfully created.' }
        format.json { render :show, status: :created, location: @poke_user }
      else
        format.html { render :new }
        format.json { render json: @poke_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poke_users/1
  # PATCH/PUT /poke_users/1.json
  def update
    respond_to do |format|
      if @poke_user.update(poke_user_params)
        format.html { redirect_to @poke_user, notice: 'Poke user was successfully updated.' }
        format.json { render :show, status: :ok, location: @poke_user }
      else
        format.html { render :edit }
        format.json { render json: @poke_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poke_users/1
  # DELETE /poke_users/1.json
  def destroy
    @poke_user.destroy
    respond_to do |format|
      format.html { redirect_to poke_users_url, notice: 'Poke user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def lvlup
    @poke_user.level += 1
    @poke_user.save
    redirect_to user_poke_users_path(current_user)
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poke_user
      @poke_user = PokeUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poke_user_params
      params.require(:poke_user).permit(:level, :pokemon_id)
    end
end

app/helpers/poke_users_helper.rb
module PokeUsersHelper
end

app/views/poke_users/_form.html.erb
<%= form_for(@poke_user) do |f| %>
  <% if @poke_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poke_user.errors.count, "error") %> prohibited this poke_user from being saved:</h2>

      <ul>
      <% @poke_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poke_users/edit.html.erb
<h1>Editing Poke User</h1>

<%= render 'form' %>

<%= link_to 'Show', @poke_user %> |
<%= link_to 'Back', poke_users_path %>

app/views/poke_users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-6">
<h1> Pokemons de: <%= @user.name %> </h1>
<%= link_to 'New Poke user', new_poke_user_path %>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poke_users.each do |poke_user| %>
      <tr>
        <td><%= poke_user.pokemon.name %></td>
        <td><%= poke_user.pokemon.description %></td>
        <td><%= poke_user.level %></td>
        <td><%= link_to "+1", lvlup_user_poke_user_path(current_user, poke_user) %> 
        <td><%= link_to 'Show', poke_user %></td>
        <td><%= link_to 'Edit', edit_poke_user_path(poke_user) %></td>
        <td><%= link_to 'Destroy', poke_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<% if (params[:user_id].to_i == current_user.id) %>
  <div class="col-md-6">
    <div class="well">
    <% Pokemon.all.each do |pokemon| %>
      <p>
        <%= form_for(PokeUser.new) do |f| %>
          <%= f.label :pokemon_id, pokemon.name %>
          <%= f.hidden_field :pokemon_id, value: pokemon.id %>
          <%= f.submit "Agregar", class:"btn btn-primary btn-sm" %>
        <% end %>
      </p>
    <% end %>
  </div>
  </div>
<% end %>

app/views/poke_users/new.html.erb
<h1>New Poke User</h1>

<%= render 'form' %>

<%= link_to 'Back', poke_users_path %>

app/views/poke_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Level:</strong>
  <%= @poke_user.level %>
</p>

<%= link_to 'Edit', edit_poke_user_path(@poke_user) %> |
<%= link_to 'Back', poke_users_path %>